### ISSUE TITLE
Error with eleventy-image 4.0: munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by madrilene** [solution-loisir/markdown-it-eleventy-img#70]
I got a runtime error when using with eleventy-image version 4.0 in a project: 

```
munmap_chunk(): invalid pointer
Aborted (core dumped)
ERROR: "dev:11ty" exited with 134.
```

I bypassed the issue by updating the `markdown-it-eleventy-img` package's own dependency of `eleventy-image` to version 4.0.

**Comment by solution-loisir** [comment]
Sorry about that. I'll update dependencies during lunch.

**Comment by madrilene** [comment]
Don't worry at all! Thank you for your time and your work!

**Comment by solution-loisir** [comment]
I ran into a `sharp` problem while updating dependencies. I'll have to look into it this evening. Thanks for your patience!
```bash
Error: Could not load the "sharp" module using the linux-x64 runtime
  Possible solutions:
  - Ensure optional dependencies can be installed:
      npm install --include=optional sharp
      yarn add sharp --ignore-engines
  - Ensure your package manager supports multi-platform installation:
      See https://sharp.pixelplumbing.com/install#cross-platform
  - Add platform-specific dependencies:
      npm install --os=linux --cpu=x64 sharp
  - Consult the installation documentation:
      See https://sharp.pixelplumbing.com/install
```

**Comment by solution-loisir** [comment]
Updated @11ty/eleventy-img to latest (4.0.2). You may use v0.10.2 release. Feel free to reopen if there's something wrong. Thanks for your contribution! :open_hands:

**Comment by madrilene** [comment]
Thank you!!
