### ISSUE TITLE
How Prevent GIF Images from Being Processed by markdownItEleventyImg Plugin?

### ISSUE THREAD

**Issue by joisun** [solution-loisir/markdown-it-eleventy-img#81]
Hello, Thanks for the awesome plugin.  

I am using Eleventy to write a blog and I have configured markdownItEleventyImg to handle images in my markdown files. My current configuration looks like this:

```js
const path = require('path');

markdownLib.use(markdownItEleventyImg, 
    {
    imgOptions: {
        widths: [1200],
        urlPath: `/${SITE_PREFIX}/images/`,
        outputDir: "./_site/images/",
        formats: ["jpeg", "gif"],
        sharpOptions: {
            animated: true,
        },
        // sharpJpegOptions:{
        //     quality:100
        // }
    },
    globalAttributes: {
        class: "markdown-image",
        decoding: "async",
        sizes: "100vw"
    },
    resolvePath: (filepath, env) => path.join(path.dirname(env.page.inputPath), filepath)
});
```

However, I have encountered an issue where all images, including GIFs, are processed and output in the specified formats. My intention is to exclude GIF images from being processed by this plugin, while still processing other image formats like JPEG.

I have attempted to adjust the configuration but haven't been successful in preventing GIFs from being processed.

Could you please provide guidance on how to configure markdownItEleventyImg to skip GIF images during processing (just generate the corret path)? 

> by the way, If my post have more then one gif asset, only the first one will be animated, which i have no idea too.

Thank you!

**Comment by solution-loisir** [comment]
Hi @jaycethanks, from the code you provided, your HTML output is probably a `<picture>` element with the first `srcset` from the top a `jpeg` and the second `srcset` down a `gif` image. Now I'm not sure that's the output you want. To put the `gif` on top you have to list it first as `["gif", "jpeg"]`. You could also just do `["auto"]`. I'm not sure what you want to achieve with the plugin. What problem is it solving for you?

**Comment by solution-loisir** [comment]
Just to answer your question directly: md image token will always be processed by the plugin. You can use the [renderImage](https://github.com/solution-loisir/markdown-it-eleventy-img?tab=readme-ov-file#custom-image-rendering) option to filter gifs and render the right output for your need.

**Comment by joisun** [comment]
> Just to answer your question directly: md image token will always be processed by the plugin. You can use the [renderImage](https://github.com/solution-loisir/markdown-it-eleventy-img?tab=readme-ov-file#custom-image-rendering) option to filter gifs and render the right output for your need.

Thanks for your attention, what I want to do by simply saying that I don't want the plugin to handle gif assets, but only resolve the path which like copy to the image folder I guess?  By the current configuration above, all assets were processed and output both gif and jpeg, however the output for gif jpeg is not necessary and most important, the output gif is not all working well, only the first gif asset is animated, while others in the same post is not. Thanks again!

**Comment by solution-loisir** [comment]
Have you tried `formats: ["auto"]`? I suggest that you inspect the HTML output and see if you get what you want. You can share here if you want.

**Comment by jaycethanks** [comment]
> Have you tried `formats: ["auto"]`? I suggest that you inspect the HTML output and see if you get what you want. You can share here if you want.

Okay, I'll show you.

1. config 1:
```js
    markdownLib.use(markdownItEleventyImg, {
        imgOptions: {
            widths: [1200],
            urlPath: `/${SITE_PREFIX}/images/`,
            outputDir: "./_site/images/",
            formats: ["jpeg","gif"],
            sharpOptions: {
                animated: true,
            },
        },
        globalAttributes: {
            class: "markdown-image",
            decoding: "async",
            sizes: "100vw"
        },
        resolvePath: (filepath, env) => path.join(path.dirname(env.page.inputPath), filepath)
    })
```
Page of config1:
![image](https://github.com/solution-loisir/markdown-it-eleventy-img/assets/44388103/fa398b0d-eb93-432e-adc8-3d85d7d6e82f)
![image](https://github.com/solution-loisir/markdown-it-eleventy-img/assets/44388103/f408528c-d3a5-4193-9dfd-2ed85387c643)

And the console appears many size limited errors like:
![image](https://github.com/solution-loisir/markdown-it-eleventy-img/assets/44388103/81a08f32-0cbd-47fb-91f2-c9ffc0fd3e1f)

Output Dir of config1:
![image](https://github.com/solution-loisir/markdown-it-eleventy-img/assets/44388103/c337ab68-915f-4c9d-913d-982cf6da2576)

2. config 2:
```js
    markdownLib.use(markdownItEleventyImg, {
        imgOptions: {
            widths: [1200],
            urlPath: `/${SITE_PREFIX}/images/`,
            outputDir: "./_site/images/",
            formats: ["auto"],
            sharpOptions: {
                animated: true,
            },
        },
        globalAttributes: {
            class: "markdown-image",
            decoding: "async",
            sizes: "100vw"
        },
        resolvePath: (filepath, env) => path.join(path.dirname(env.page.inputPath), filepath)
    })
```
Page of config1:
the same with config1, and the same error occurs in console as config1.
![image](https://github.com/solution-loisir/markdown-it-eleventy-img/assets/44388103/91a47935-1248-47ea-9cf1-af9945f012d8)

Output Dir of config2:
![image](https://github.com/solution-loisir/markdown-it-eleventy-img/assets/44388103/4e997dba-97b0-44f2-b264-bfe5857f7eb9)

3. config 3:
```js
    markdownLib.use(markdownItEleventyImg, {
        imgOptions: {
            widths: [1200],
            urlPath: `/${SITE_PREFIX}/images/`,
            outputDir: "./_site/images/",
            formats: ["auto"],
            // sharpOptions: {
            //     animated: true,
            // },
        },
        globalAttributes: {
            class: "markdown-image",
            decoding: "async",
            sizes: "100vw"
        },
        resolvePath: (filepath, env) => path.join(path.dirname(env.page.inputPath), filepath)
    })
```
Page of config 3：
![image](https://github.com/solution-loisir/markdown-it-eleventy-img/assets/44388103/ae747e87-d50a-4a83-bfa6-6d176f8f4c26)

There is no error occured in console. 


And you can checkout the related public repository if needed .

https://github.com/jaycethanks/blog_11ty ❤️

**Comment by joisun** [comment]
> Have you tried `formats: ["auto"]`? I suggest that you inspect the HTML output and see if you get what you want. You can share here if you want.

Thanks. solved by:
```js
    sharpOptions: {
                animated: true,
                limitInputPixels:false
            },
```
